name: mancala_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^3.1.1
  json_annotation: ^4.6.0
  logger: any  #for logging purpose
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1 

flutter:
  uses-material-design: true
